name: ${project.artifactId}
authors: ${project.authors}
version: ${major.version}.b${buildNumber}
main: ${project.main}
load: POSTWORLD
softdepend: [Multiverse-Core]
permissions:
    xpstorage.create.*:
        description: Ability to create xpsigns
        default: true
        children: 
            xpstorage.create.localplayer: true
            xpstorage.create.enderplayer: true
            xpstorage.create.localgroup: true
            xpstorage.create.endergroup: true
    xpstorage.create.localplayer:
        description: Ability to create local player signs
        default: true
    xpstorage.create.enderplayer:
        description: Ability to create ender player signs
        default: true
    xpstorage.create.localgroup:
        description: Ability to create local group signs
        default: true
    xpstorage.create.endergroup:
        description: Ability to create ender group signs (players can only change into this sign so they need at least one other create pemission to use this one)
        default: true
    xpstorage.createnewgroup:
        description: Gives the ability to create a new group
        default: true
    xpstorage.openguiothers:
        description: Gives a player to open the gui of a sign from other players. Owner specific items and abilities are still hidden.
        default: false
    xpstorage.changeowner:
        description: Intended for moderators. This to change a sign from one owner to another. For group sings this is already an option in the edit player list.
        default: op
    xpstorage.xpreloadgui:
        description: Reloads the plugin GUI
        default: op
    xpstorage.showuuid:
        description: Shows the uuid of the owner and sign on the head
        default: op
    xpstorage.xpstorage:
        description: Access to the help page of XPStorage
        default: true
commands:
    xpreloadgui:
        description: Reloads the XPStorage GUI file
        usage: /xpreloadgui
        permission: xpStorage.xpreloadgui
    xpstorage:
        description: Get help page of XPStorage
        usage: /xpstorage
        permission: xpStorage.xpstorage