name: ${project.artifactId}
authors: ${project.authors}
version: ${major.version}.b${buildNumber}
main: ${project.main}
load: POSTWORLD
permissions:
    xpStorage.createXpGroup:
        description: Gives the ability to create groups
        default: true
    xpstorage.openGuiOthers:
        description: Gives a player to open the gui of a sign from other players. Owner specific items and abilities are still hidden.
        default: false
    xpstorage.changeOwner:
        description: Intended for moderators. This to change a sign from one owner to another. For groups and shared signs this is an default option in the edit player list.
        default: op
    xpstorage.xpreloadgui:
        description: Reloads the plugin GUI
        default: op
    xpstorage.showuuid:
        description: Shows the uuid of the owner and sign on the head
        default: op
    xpStorage.xpstorage:
        description: Access to the help page of XPStorage
        default: true
commands:
    xpreloadgui:
        description: Reloads the XPStorage GUI file
        usage: /xpreloadgui
        permission: xpStorage.xpreloadgui
    xpstorage:
        description: Get help page of XPStorage
        usage: /xpstorage
        permission: xpStorage.xpstorage