name: ${project.artifactId}
authors: ${project.authors}
version: ${major.version.version}.b${buildNumber}
main: ${project.main}
commands:
   createXpGroup:
      description: This command creates a group.
      usage: /<command> [Group name]
      permission: xpStorage.createXpGroup
      permission-message: You don't have permission to create a XpGroup